lexer grammar TSqlLexer;

// Case-insensitive alphabet fragments
fragment A: [aA];
fragment B: [bB];
fragment C: [cC];
fragment D: [dD];
fragment E: [eE];
fragment F: [fF];
fragment G: [gG];
fragment H: [hH];
fragment I: [iI];
fragment J: [jJ];
fragment K: [kK];
fragment L: [lL];
fragment M: [mM];
fragment N: [nN];
fragment O: [oO];
fragment P: [pP];
fragment Q: [qQ];
fragment R: [rR];
fragment S: [sS];
fragment T: [tT];
fragment U: [uU];
fragment V: [vV];
fragment W: [wW];
fragment X: [xX];
fragment Y: [yY];
fragment Z: [zZ];

// Keywords
SELECT: S E L E C T;
FROM: F R O M;
WHERE: W H E R E;
INSERT: I N S E R T;
INTO: I N T O;
UPDATE: U P D A T E;
DELETE: D E L E T E;
MERGE: M E R G E;
SET: S E T;
VALUES: V A L U E S;
CREATE: C R E A T E;
ALTER: A L T E R;
DROP: D R O P;
TABLE: T A B L E;
VIEW: V I E W;
PROCEDURE: P R O C E D U R E;
PROC: P R O C;
FUNCTION: F U N C T I O N;
TRIGGER: T R I G G E R;
INDEX: I N D E X;
PRIMARY: P R I M A R Y;
KEY: K E Y;
FOREIGN: F O R E I G N;
REFERENCES: R E F E R E N C E S;
CONSTRAINT: C O N S T R A I N T;
CHECK: C H E C K;
UNIQUE: U N I Q U E;
DEFAULT: D E F A U L T;
NULL: N U L L;
NOT: N O T;
AND: A N D;
OR: O R;
AS: A S;
ON: O N;
JOIN: J O I N;
INNER: I N N E R;
LEFT: L E F T;
RIGHT: R I G H T;
FULL: F U L L;
OUTER: O U T E R;
CROSS: C R O S S;
GROUP: G R O U P;
BY: B Y;
HAVING: H A V I N G;
ORDER: O R D E R;
ASC: A S C;
DESC: D E S C;
TOP: T O P;
DISTINCT: D I S T I N C T;
ALL: A L L;
UNION: U N I O N;
EXCEPT: E X C E P T;
INTERSECT: I N T E R S E C T;
EXISTS: E X I S T S;
IN: I N;
LIKE: L I K E;
BETWEEN: B E T W E E N;
IS: I S;
USING: U S I N G;
MATCHED: M A T C H E D;
FOR: F O R;
CASE: C A S E;
WHEN: W H E N;
THEN: T H E N;
ELSE: E L S E;
END: E N D;
BEGIN: B E G I N;
TRAN: T R A N;
TRANSACTION: T R A N S A C T I O N;
COMMIT: C O M M I T;
ROLLBACK: R O L L B A C K;
TRY: T R Y;
CATCH: C A T C H;
IF: I F;
WHILE: W H I L E;
DECLARE: D E C L A R E;
EXEC: E X E C;
EXECUTE: E X E C U T E;
CURSOR: C U R S O R;
OPEN: O P E N;
FETCH: F E T C H;
CLOSE: C L O S E;
DEALLOCATE: D E A L L O C A T E;
NEXT: N E X T;
WITH: W I T H;
NOLOCK: N O L O C K;
READUNCOMMITTED: R E A D U N C O M M I T T E D;
READCOMMITTED: R E A D C O M M I T T E D;
REPEATABLEREAD: R E P E A T A B L E R E A D;
SERIALIZABLE: S E R I A L I Z A B L E;
HOLDLOCK: H O L D L O C K;
UPDLOCK: U P D L O C K;
TABLOCK: T A B L O C K;
TABLOCKX: T A B L O C K X;
PAGLOCK: P A G L O C K;
ROWLOCK: R O W L O C K;
NOWAIT: N O W A I T;
OPTION: O P T I O N;
RECOMPILE: R E C O M P I L E;
GO: G O;
USE: U S E;
PRINT: P R I N T;
RAISERROR: R A I S E R R O R;
THROW: T H R O W;
RETURN: R E T U R N;
RETURNS: R E T U R N S;
OUTPUT: O U T P U T;
OUT: O U T;
XACT_ABORT: X A C T '_' A B O R T;
NOCOUNT: N O C O U N T;
IDENTITY: I D E N T I T Y;
COLLATE: C O L L A T E;
CAST: C A S T;
CONVERT: C O N V E R T;
COALESCE: C O A L E S C E;
ISNULL: I S N U L L;
NULLIF: N U L L I F;
OVER: O V E R;
PARTITION: P A R T I T I O N;
ROW_NUMBER: R O W '_' N U M B E R;
RANK: R A N K;
DENSE_RANK: D E N S E '_' R A N K;
MAX: M A X;
VALUE: V A L U E;
TYPE: T Y P E;
STATUS: S T A T U S;
COUNT: C O U N T;

// Symbols
SEMI: ';';
COMMA: ',';
DOT: '.';
LPAREN: '(';
RPAREN: ')';
PLUS: '+';
MINUS: '-';
STAR: '*';
SLASH: '/';
PERCENT: '%';
EQUAL: '=';
NOT_EQUAL: '<>' | '!=';
LESS_THAN: '<';
LESS_EQUAL: '<=';
GREATER_THAN: '>';
GREATER_EQUAL: '>=';
AT: '@';
COLON: ':';

// Literals & Identifiers
STRING_LITERAL: ( 'N' | 'n' )? '\'' ( '\'\'' | ~['\r\n] )* '\'';
INT_LITERAL: [0-9]+;
DECIMAL_LITERAL: [0-9]+ '.' [0-9]+;

VARIABLE: '@' [a-zA-Z0-9_#$]+;
TEMP_TABLE_ID: '#' [a-zA-Z0-9_#$]+ | '##' [a-zA-Z0-9_#$]+;
BRACKET_ID: '[' ~['\r\n\]]+ ']';
QUOTED_ID: '"' ~['\r\n"]+ '"';
ID: [a-zA-Z_] [a-zA-Z0-9_#$]*;

// Whitespace and Comments
LINE_COMMENT: '--' ~[\r\n]* -> channel(HIDDEN);
BLOCK_COMMENT: '/*' .*? '*/' -> channel(HIDDEN);
WS: [ \t\r\n]+ -> channel(HIDDEN);
