lexer grammar OracleLexer;

fragment A: [aA];
fragment B: [bB];
fragment C: [cC];
fragment D: [dD];
fragment E: [eE];
fragment F: [fF];
fragment G: [gG];
fragment H: [hH];
fragment I: [iI];
fragment J: [jJ];
fragment K: [kK];
fragment L: [lL];
fragment M: [mM];
fragment N: [nN];
fragment O: [oO];
fragment P: [pP];
fragment Q: [qQ];
fragment R: [rR];
fragment S: [sS];
fragment T: [tT];
fragment U: [uU];
fragment V: [vV];
fragment W: [wW];
fragment X: [xX];
fragment Y: [yY];
fragment Z: [zZ];

SELECT: S E L E C T;
FROM: F R O M;
WHERE: W H E R E;
INTO: I N T O;
INSERT: I N S E R T;
UPDATE: U P D A T E;
SET: S E T;
DELETE: D E L E T E;
VALUES: V A L U E S;
MERGE: M E R G E;
USING: U S I N G;
ON: O N;
WHEN: W H E N;
MATCHED: M A T C H E D;
NOT: N O T;
THEN: T H E N;
CREATE: C R E A T E;
OR: O R;
REPLACE: R E P L A C E;
ALTER: A L T E R;
ADD: A D D;
MODIFY: M O D I F Y;
DROP: D R O P;
TABLE: T A B L E;
COLUMN: C O L U M N;
VIEW: V I E W;
MATERIALIZED: M A T E R I A L I Z E D;
INDEX: I N D E X;
SEQUENCE: S E Q U E N C E;
SYNONYM: S Y N O N Y M;
PROCEDURE: P R O C E D U R E;
FUNCTION: F U N C T I O N;
PACKAGE: P A C K A G E;
TRIGGER: T R I G G E R;
TYPE: T Y P E;
AS: A S;
IS: I S;
DECLARE: D E C L A R E;
BEGIN: B E G I N;
END: E N D;
EXCEPTION: E X C E P T I O N;
WHEN_KW: W H E N;
LOOP: L O O P;
IF: I F;
ELSIF: E L S I F;
ELSE: E L S E;
FOR: F O R;
WHILE: W H I L E;
OPEN: O P E N;
CLOSE: C L O S E;
FETCH: F E T C H;
COMMIT: C O M M I T;
ROLLBACK: R O L L B A C K;
SAVEPOINT: S A V E P O I N T;
RETURN: R E T U R N;
NULL: N U L L;
PRIMARY: P R I M A R Y;
KEY: K E Y;
FOREIGN: F O R E I G N;
REFERENCES: R E F E R E N C E S;
CONSTRAINT: C O N S T R A I N T;
UNIQUE: U N I Q U E;
CHECK: C H E C K;
DEFAULT: D E F A U L T;
NOT_NULL: N O T [ \t\r\n]+ N U L L;
DISTINCT: D I S T I N C T;
GROUP: G R O U P;
ORDER: O R D E R;
BY: B Y;
HAVING: H A V I N G;
CONNECT: C O N N E C T;
START: S T A R T;
WITH: W I T H;
PRIOR: P R I O R;
ROWNUM: R O W N U M;
OVER: O V E R;
PARTITION: P A R T I T I O N;
INCREMENT: I N C R E M E N T;
MAXVALUE: M A X V A L U E;
NOMAXVALUE: N O M A X V A L U E;
MINVALUE: M I N V A L U E;
NOMINVALUE: N O M I N V A L U E;
CACHE: C A C H E;
NOCACHE: N O C A C H E;
CYCLE: C Y C L E;
NOCYCLE: N O C Y C L E;
NOORDER: N O O R D E R;

STAR: '*';
COMMA: ',';
DOT: '.';
SEMICOLON: ';';
SLASH: '/';
LPAREN: '(';
RPAREN: ')';
LBRACK: '[';
RBRACK: ']';
COLON: ':';
ASSIGN: ':=';
EQ: '=';
NEQ: '!=' | '<>';
LTE: '<=';
GTE: '>=';
LT: '<';
GT: '>';
PLUS: '+';
MINUS: '-';
CONCAT: '||';

NUMBER: [0-9]+ ('.' [0-9]+)?;
STRING: '\'' (~'\'' | '\'\'')* '\'';
QUOTED_IDENTIFIER: '"' (~'"' | '""')* '"';
IDENTIFIER: [a-zA-Z_][a-zA-Z0-9_$#]*;

LINE_COMMENT: '--' ~[\r\n]* -> channel(HIDDEN);
BLOCK_COMMENT: '/*' .*? '*/' -> channel(HIDDEN);
WS: [ \t\r\n]+ -> channel(HIDDEN);
